---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
DATA_PATH = "~/Documents/semantic_difference/data/L665/"
intro_methods_sim <- read_csv(paste0(DATA_PATH, "intro_methods_interword_similarity.csv"))
intro_discussion_sim <- read_csv(paste0(DATA_PATH, "intro_discussion_interword_similarity.csv"))
methods_discussion_sim <- read_csv(paste0(DATA_PATH, "methods_discussion_interword_similarity.csv"))

semaxis_data <- read_csv(paste0(DATA_PATH, "semantic_word_axes.csv"))

intro_methods_ft <- read_csv(paste0(DATA_PATH, "intro_methods_interword_similarity_ft.csv"))
intro_discussion_ft <- read_csv(paste0(DATA_PATH, "intro_discussion_interword_similarity_ft.csv"))
methods_discussion_ft <- read_csv(paste0(DATA_PATH, "methods_discussion_interword_similarity_ft.csv"))
```

```{r}
intro_methods_ordered <- intro_methods_sim %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

intro_methods_ordered
```

```{r}
intro_methods_sim %>%
  mutate(
    word = factor(word, levels = levels(intro_methods_ordered$word.ord))
  ) %>%
  arrange(word) %>%
  ggplot(aes(x = x, y = y, group = word)) +
  geom_point(alpha = 0.001) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~word) +
  geom_smooth() +
  geom_text(data = intro_methods_ordered, x = 0.1, y = 0.8, aes(group = word.ord, label = round(r, 3))) +
  theme_bw() +
  labs(x = "Intro Model",
       y = "Methods Model")
  
```

```{r}
intro_discussion_ordered <- intro_discussion_sim %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))


methods_discussion_ordered <- methods_discussion_sim %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

```



```{r}
intro_methods_ordered$type = "intro-methods"
intro_discussion_ordered$type = "intro-discussion"
methods_discussion_ordered$type = "methods-discussion"

combined_words <- rbind(intro_methods_ordered, intro_discussion_ordered, methods_discussion_ordered) %>%
  mutate(type = factor(type, levels = c("intro-methods", "intro-discussion", "methods-discussion")))


word_levels = c("should", "may", "indicate", "might", "assume", "seem", "appear", "must",
                "will", "cannot", "report", "would", "could", "predict", "propose", "suggest")

p <- combined_words %>%
  mutate(word = factor(word, levels = word_levels),
         type = factor(type)) %>%
  ggplot(aes(x = type, y = r, color = type, shape = type)) +
  geom_point(size = 3) +
  facet_wrap(~word, nrow = 2) +
  theme_bw() +
  scale_shape_discrete(name = "Section comparison") +
  scale_color_discrete(name = "Section comparison") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "bottom"
  ) +
  labs(
    y = "R-squared of word similarities between two models"
  )

p
```


```{r}
library(broom)
library(tidyr)

# order by the biggest difference
semaxis_plot <- semaxis_data %>%
  filter(word %in% c("must", "indicate", "propose")) %>%
  mutate(
    intro_meth_diff = abs(intro - methods),
    antonym = factor(antonym),
    antonym = reorder(antonym, intro),
    word = factor(word, labels = c("\"Must\"", "\"Indicate\"", "\"Propose\""))
  ) %>%
  group_by(antonym, word) %>%
  mutate(
    minval = min(intro, methods, discussion),
    maxval = max(intro, methods, discussion),
    ystart = ifelse(min(intro, methods, discussion) == intro, intro, methods),
    yend = discussion
  ) %>%
  gather(key, value, intro, methods, discussion) %>%
  mutate(key = factor(key, levels = c("intro", "methods", "discussion"))) %>%
  ggplot(aes(x = antonym, y = value, shape = key, color = key)) +
  geom_segment(aes(x = antonym, xend = antonym, y = minval, yend = maxval), color = "black", alpha = 0.6) +
  geom_point(size = 3) +
  coord_flip() +
  facet_wrap(~word) +
  geom_hline(yintercept = 0, color = "darkgrey") +
  scale_shape_manual(name = "Trained context", values = c(19, 17, 18)) +
  scale_color_manual(name = "Trained context", values = c('#3498db', '#e74c3c', '#8e44ad')) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        legend.position = "bottom") +
  labs(y = "Position on axis")

semaxis_plot
```

```{r}
intro_methods_ordered <- intro_methods_ft %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

intro_discussion_ordered <- intro_discussion_ft %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

methods_discussion_ordered <- methods_discussion_ft %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))


intro_methods_ordered$type = "intro-methods"
intro_discussion_ordered$type = "intro-discussion"
methods_discussion_ordered$type = "methods-discussion"

combined_words <- rbind(intro_methods_ordered, intro_discussion_ordered, methods_discussion_ordered) %>%
  mutate(type = factor(type, levels = c("intro-methods", "intro-discussion", "methods-discussion")))


word_levels = c("should", "may", "indicate", "might", "assume", "seem", "appear", "must",
                "will", "cannot", "report", "would", "could", "predict", "propose", "suggest")

p <- combined_words %>%
  mutate(word = factor(word, levels = word_levels),
         type = factor(type)) %>%
  ggplot(aes(x = type, y = r, color = type, shape = type)) +
  geom_point(size = 3) +
  facet_wrap(~word, nrow = 2) +
  theme_bw() +
  scale_shape_discrete(name = "Section comparison") +
  scale_color_discrete(name = "Section comparison") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "bottom"
  ) +
  labs(
    y = "R-squared of word similarities between two models"
  )

p
```
