---
title: "R Notebook"
output: html_notebook
---

```{r}

library(readr)
library(dplyr)
library(ggplot2)

# Need to run 20190419_SemAxisExample.ipynb before running this. 
semaxis_data <- read_csv("../data/semantic_word_axes.csv")
intro_methods_sim <- read_csv("../data/intro_method_interword_similarity.csv")
```

```{r}
intro_methods_ordered <- intro_methods_sim %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

intro_methods_ordered
```

```{r}
intro_methods_sim %>%
  mutate(
    word = factor(word, levels = levels(intro_methods_ordered$word.ord))
  ) %>%
  arrange(word) %>%
  ggplot(aes(x = x, y = y, group = word)) +
  geom_point(alpha = 0.001) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~word) +
  geom_smooth() +
  geom_text(data = intro_methods_ordered, x = 0.1, y = 0.8, aes(group = word.ord, label = round(r, 3))) +
  theme_bw() +
  labs(x = "Intro Model",
       y = "Methods Model")
  
```

```{r}
intro_discussion_sim <- read_csv("../data/intro_discussion_interword_similarity.csv")

intro_discussion_ordered <- intro_discussion_sim %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))

intro_discussion_ordered
```


```{r}
intro_discussion_sim %>%
  mutate(
    word = factor(word, levels = levels(intro_discussion_ordered$word.ord))
  ) %>%
  arrange(word) %>%
  ggplot(aes(x = x, y = y, group = word)) +
  geom_point(alpha = 0.001) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~word) +
  geom_smooth() +
  geom_text(data = intro_discussion_ordered, x = 0.1, y = 0.8, aes(group = word.ord, label = round(r, 3))) +
  theme_bw() +
  labs(x = "Intro Model",
       y = "Discussion Model")
```

```{r}
intro_methods_ordered$type = "intro-methods"
intro_discussion_ordered$type = "intro-discussion"

combined_words <- rbind(intro_methods_ordered, intro_discussion_ordered) %>%
  mutate(type = factor(type, levels = c("intro-methods", "intro-discussion")))


word_levels = c("approach", "finding", "literature", "method", "observation", "result", "significant", "study", "theory")

p <- combined_words %>%
  mutate(word = factor(word, levels = word_levels),
         type = factor(type)) %>%
  ggplot(aes(x = type, y = r, color = type, shape = type)) +
  geom_point(size = 2.5) +
  facet_wrap(~word, nrow = 3, ncol = 3) +
  theme_bw() +
  scale_shape_discrete(name = "Section comparison") +
  scale_color_discrete(name = "Section comparison") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "bottom"
  ) +
  labs(
    y = "R-squared of word similarities between two models"
  )

p
```


```{r}
library(broom)
library(tidyr)

# order by the biggest difference
semaxis_data %>%
  filter(word %in% c("theory", "study")) %>%
  mutate(
    intro_meth_diff = abs(intro - methods),
    antonym = factor(antonym),
    antonym = reorder(antonym, intro_meth_diff),
    ystart = intro,
    yend = methods,
    word = factor(word, labels = c("\"Theory\"", "\"Study\""))
  ) %>%
  gather(key, value, intro, methods, discussion) %>%
  filter(key %in% c("intro", "methods")) %>%
  ggplot(aes(x = antonym, y = value, shape = key, color = key)) +
  geom_segment(aes(x = antonym, xend = antonym, y = ystart, yend = yend), color = "black") +
  geom_point(size = 3) +
  coord_flip() +
  facet_wrap(~word) +
  geom_hline(yintercept = 0, color = "black") +
  scale_shape_manual(name = "Trained context", values = c(18, 19)) +
  scale_color_manual(name = "Trained context", values = c('#3498db', '#e67e22')) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        legend.position = "bottom") +
  labs(y = "Position on axis")
```


## Now repeat with the Yelp data
```{r}

library(readr)
library(dplyr)
library(ggplot2)

yelp_data <- read_csv("../data/restaurant_pos_neg_interword_similarity.csv")


yelp_ordered <- yelp_data %>%
  group_by(word) %>%
  summarize(
    r = cor(x, y) ^ 2
  ) %>%
  arrange(r) %>%
  mutate(word.ord = factor(word, levels = word[order(desc(r))]))


yelp_data %>%
  mutate(
    word = factor(word, levels = levels(yelp_ordered$word.ord))
  ) %>%
  arrange(word) %>%
  ggplot(aes(x = x, y = y, group = word)) +
  geom_point(alpha = 0.001) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~word) +
  geom_smooth() +
  geom_text(data = yelp_ordered, x = 0.1, y = 0.8, aes(group = word.ord, label = round(r, 3))) +
  theme_minimal() +
  labs(x = "Hotel Model",
       y = "Restaurant Model")

```

```{r}
yelp_ordered %>%
  mutate(word = factor(word, levels = word[order(desc(r))])) %>%
  ggplot(aes(x = word, y = r)) +
  geom_bar(stat = "identity", fill = "#8e44ad", color = "black", alpha = 0.7)  +
  theme_minimal() +
  theme(axis.title.x = element_blank()) +
  labs(y = "R-squared of word similarities between two models")
```



```{r}

library(broom)
library(tidyr)

yelp_semaxis_data <- read_csv("../data/yelp_semantic_word_axes.csv")

# order by the biggest difference
yelp_semaxis_data %>%
  filter(word %in% c("client", "table")) %>%
  mutate(
    diff_axes = abs(hotel - restaurant),
    antonym = factor(antonym),
    antonym = reorder(antonym, diff_axes),
    ystart = hotel,
    yend = restaurant,
    # word = factor(word, labels = c("\"Client\"", "\"Table\""))
  ) %>%
  gather(key, value, hotel, restaurant) %>%
  ggplot(aes(x = antonym, y = value, shape = key, color = key)) +
  geom_segment(aes(x = antonym, xend = antonym, y = ystart, yend = yend), color = "black") +
  geom_point(size = 3) +
  coord_flip() +
  facet_wrap(~word) +
  geom_hline(yintercept = 0, color = "black") +
  scale_shape_manual(name = "Trained context", values = c(18, 19)) +
  scale_color_manual(name = "Trained context", values = c('#3498db', '#e67e22')) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        legend.position = "bottom") +
  labs(y = "Position on axis")
```

